# Generated by Django 4.2.2 on 2023-06-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ciudad')),
                ('code', models.IntegerField(verbose_name='Código postal')),
                ('population', models.IntegerField(verbose_name='Población')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_date', models.DateTimeField(verbose_name='Formatted Date')),
                ('summary', models.CharField(max_length=120, verbose_name='Summary')),
                ('precip_type', models.CharField(max_length=260, verbose_name='Precip Type')),
                ('temperature_c', models.FloatField(verbose_name='Temperature (C)')),
                ('apparent_temperature_c', models.FloatField(verbose_name='Apparent Temperature (C)')),
                ('humity', models.FloatField(verbose_name='Humity')),
                ('wind_speed', models.FloatField(verbose_name='Wind Speed (km/h)')),
                ('wind_bearing', models.FloatField(verbose_name='Wind Bearing (degrees)')),
                ('visibility', models.FloatField(verbose_name='Visibility')),
                ('loud_cover', models.IntegerField(verbose_name='Loud Cover')),
                ('pressure', models.FloatField(verbose_name='Pressure (millibars)')),
                ('daily_summary', models.CharField(max_length=260, verbose_name='Daily Summary')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weathers', to='weather.city')),
            ],
        ),
    ]
